FROM quay.io/jupyter/base-notebook
USER root

# Install the bash kernelssss
RUN pip install bash_kernel && \
    python -m bash_kernel.install

    #adding jovyan to group
RUN groupadd -r jovyan
#setting permessions
RUN chmod +w /home/jovyan/.ipython
RUN chown jovyan:jovyan /home/jovyan/.ipython
#Environment variables
ENV PYDEVD_DISABLE_FILE_VALIDATION=1
USER jovyan

# Set the working directory
WORKDIR /home/jovyan/work

# Expose the default port
EXPOSE 8888

# Start the container
ENTRYPOINT ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--NotebookApp.token=''"]
