# Use the official Jupyter Notebook image as the base image
FROM jupyter/scipy-notebook:latest

# Install Java
USER root
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get clean

# Install coursier
USER $NB_UID
RUN curl -Lo coursier https://git.io/coursier-cli && \
    chmod +x coursier

# Install Almond kernel
#RUN ./coursier launch --fork almond -- --install && \
RUN ./coursier launch --fork almond:0.10.0 --scala 2.12.11 -- --install --display-name "Scala (2.12)"
RUN ./coursier launch --fork almond:0.13.14 --scala 3.1.3 -- --install --id scala313 --display-name "Scala (3.3.1)"&& \
    rm -f coursier
# Expose port 8888 for Jupyter Notebook
EXPOSE 8888

# Start Jupyter Notebook
ENTRYPOINT ["jupyter", "notebook", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'"]
